# -*- coding: utf-8 -*-
"""Iris_Classification.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ihpO1jHWgbtTAav-A-M9mfVWO1JcrcRN
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

data=pd.read_csv("iris.data")

X=data.iloc[0:,:-1].values
y=data.iloc[0:,-1].values

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors = 7, metric = 'minkowski', p = 2)
classifier.fit(X_train, y_train)

y_pred = classifier.predict(X_test)

from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)